language: node_js
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta

node_js:
  - 'stable'
  - '6'
  - '5'
  - '4'

after_script:
  - npm run coveralls
